name: CI

on:
  [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Run builder script
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./build-ubuntu-remix.sh
