name: CI

on:
  [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - run:   echo ::set-env name=GHA_BRANCH::$(echo $GITHUB_REPOSITORY | awk -F / '{print $3}')
      shell: bash
    - name: Run builder script
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./build-ubuntu-remix.sh
